import { posix } from 'path';
import { LintAssertionZorn } from '../linting/lintAssertion';
import { LintAssertionOmissionInstance } from '../linting/lintAssertionOmission';
import { FileSourceInstance } from '../linting/source/fileSource';
import { typeScriptFileHasSensibleNameRule } from './assertTypeScriptFileHasSensibleName';

/**
 * Exemptions for existing files with unreadable names and no readableName annotation
 *
 * @todo fix these files and delete this exemption list
 */
export const existingUnreadableNamesExemptionList = [
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/engineEstinant3.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/engineEstinantLocator2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/engineProgram3.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/engineProgramLocator3.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/engineVoque2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/engineVoqueLocator2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/estinantVoqueRelationship2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/getEngineEstinant3.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/getEngineEstinantLocatorCollection2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/getEngineProgram3.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/getEngineProgramLocator3.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/getEngineVoque2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/getEngineVoqueLocatorCollection2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/input-output/engineEstinantInput2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/input-output/engineEstinantOutput2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/input-output/programEstinantInputRelationship.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/input-output/programEstinantOutputRelationship.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/partialEngineProgramLocator2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/programEstinantRelationship.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/engine-program/programVoqueRelationship2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/error/programError.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/error/programErrorVoictent.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/file/defaultFileGeppCombination.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/file/fileSystemNodeVoictent.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/addInteractivityToSvgDocument.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/attributeByKeyCNE.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/attributeByKeyGS.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/attributeByKeyGSC.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/attributeByKeyGSCNE.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/directedCluster2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/directedGraph2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/directedGraphEdge2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/directedGraphElement2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/directedGraphNode2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/directedSubgraph2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/getGraphvizCode.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/directed-graph/subgraphLike2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/encodeDirectedGraphAsGraphvizCode.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/graphvizCode.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/renderGraphvizCodeToSvgDocument.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/renderGraphvizCodeToSvgDocument2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/svgDocument.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/graph-visualization/svgMetadataList.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/html-file/htmlFile.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/in-memory-cache/abstractAsymmetricInMemoryVoictent2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/linting/source/estinantSource.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/output-file/outputFileVoictent.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/type-script-file/assertTypeScriptFileHasCanonialComment.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/type-script-file/comment/adapted/adaptedJsdocLikeBlockComment.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/type-script-file/comment/categorized/eslintDirectiveComment.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/type-script-file/comment/commentZorn.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/type-script-file/getExportLocatorZorn.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/type-script-file/omitProgramCanoncalExportRequirement.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/type-script-file-relationships/getSvgMetadataList.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/type-script-file-relationships/typeScriptFileRelationshipGraphZorn.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programmable-units/yaml-file/yamlFile.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-ci/assertCiFileIsUpToDate.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-ci/assertCiModelHasAllPrograms.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-ci/ciModel.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-ci/modelCi.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-ci/serializeCiModel.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-ci/serializedCiModel.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-programs/getDirectedGraphMetadataById2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-programs/getEngineEstinantGraphElements.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-programs/getEngineEstinantMetadataEntry.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-programs/getEngineProgramVoqueElements.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-programs/getEngineVoqueMetadataEntry.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/model-programs/getInputMetdataEntry.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/render-knowledge-graph/decodeAndRecastSvgDocument.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/render-knowledge-graph/dependency/fileDependencyVoictent.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/render-knowledge-graph/dependency/fileDependencyZorn.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/render-knowledge-graph/dependency/partitionedFileDependencyGroupZorn.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/render-knowledge-graph/directory/directoryFact2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/render-knowledge-graph/directory/getDirectoryFact2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/render-knowledge-graph/file/fileFact2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/render-knowledge-graph/file/getFileFact2.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/render-knowledge-graph/layer/layerZorn.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/scaffold-file/getEstinantFileContents.ts',
  'packages/voictents-and-estinants-engine/src/adapted-programs/programs/scaffold-file/getHubblepupFileContents.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/assembler/estinantAssembler.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/buildEstinant.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/left-input/leftInputHubblepupAppreffingeBuilder2.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/left-input/leftInputVoictentAppreffingeBuilder2.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/output/outputHubblepupAppreffingeBuilder2.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/output/outputHubblepupConditionalAppreffingeBuilder.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/output/outputHubblepupTupleAppreffingeBuilder2.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/pinbetunf/pinbetunfBuilder2.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/right-input/rightInputHubblepupTupleAppreffingeBuilder2.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/right-input/rightInputVoictentAppreffingeBuilder2.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/shared/estinantBuilderContext.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/shared/partialAppreffinge.ts',
  'packages/voictents-and-estinants-engine/src/adapter/estinant-builder/shared/vicken.ts',
  'packages/voictents-and-estinants-engine/src/adapter/odeshin/grition.ts',
  'packages/voictents-and-estinants-engine/src/adapter/odeshin/odeshin2.ts',
  'packages/voictents-and-estinants-engine/src/core/engine/dreanor/prected.ts',
  'packages/voictents-and-estinants-engine/src/core/types/appreffinge/input/right/croarder.ts',
  'packages/voictents-and-estinants-engine/src/core/types/appreffinge/input/right/framation.ts',
  'packages/voictents-and-estinants-engine/src/core/types/hubblepup/hubblepup.ts',
  'packages/voictents-and-estinants-engine/src/core/types/vicken/leftInputVicken.ts',
  'packages/voictents-and-estinants-engine/src/core/types/vicken/outputVicken.ts',
  'packages/voictents-and-estinants-engine/src/core/types/vicken/rightInputVicken.ts',
  'packages/voictents-and-estinants-engine/src/core/types/voque/voque.ts',
  'packages/voictents-and-estinants-engine/src/core-programs/engine-behavior/testEstinantError.ts',
  'packages/voictents-and-estinants-engine/src/core-programs/engine-behavior/testJoiningOneToVoictent.ts',
  'packages/voictents-and-estinants-engine/src/core-programs/engine-behavior/testJoiningVoictentToVoictent.ts',
  'packages/voictents-and-estinants-engine/src/core-programs/engine-behavior/testReleasingALeftVoictentMultipleTimes.ts',
  'packages/voictents-and-estinants-engine/src/core-programs/engine-behavior/testReleasingARightVoictentMultipleTimes.ts',
  'packages/voictents-and-estinants-engine/src/core-programs/engine-behavior/testUntriggeredCologyError.ts',
  'packages/voictents-and-estinants-engine/src/core-programs/engine-behavior/testVoictentInput.ts',
  'packages/voictents-and-estinants-engine/src/core-programs/serializableTypeName.ts',
  'packages/voictents-and-estinants-engine/src/core-programs/testJsonSerialization.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/deprecated-zorn/getFileZorn.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/deprecated-zorn/getVoictentResourceLocator.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/deprecated-zorn/getZorn.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/deprecated-zorn/getZornableId.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/deprecated-zorn/zornable.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/program/serializeRuntimeStatistics.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/voictent/abstractInMemoryVoictent.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/voictent/abstractSerializableVoictent.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/voictent/cachedOnDiskVoictent.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/voictent/inMemoryOdeshinVoictent2.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/voictent/inMemoryVoictent.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/voictent/jsonSerializableVoictent.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/voictent/serializableErrorVoictent.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/voictent/serializableVoictent.ts',
  'packages/voictents-and-estinants-engine/src/layer-agnostic-utilities/voque/inMemoryVoque.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/datastructure/zorn.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/json/json.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/nil/isNotNullish.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/one-way-serializer/buildSerializeableNode.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/one-way-serializer/getSerializeableNodeLineList.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/one-way-serializer/serializeableNode.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/strif/strif.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/type/spreadN.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/type-script-ast/isExportNamedTypeScriptEnumDeclaration.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/type-script-ast/isFunctionish.ts',
  'packages/voictents-and-estinants-engine/src/package-agnostic-utilities/type-script-ast/isPredicateFunctionish.ts',
].map((filePath) => {
  return new LintAssertionOmissionInstance({
    omitterSource: new FileSourceInstance({
      filePath: posix.relative('', __filename),
    }),
    omittedAssertionZorn: new LintAssertionZorn({
      rule: typeScriptFileHasSensibleNameRule,
      lintSource: new FileSourceInstance({
        filePath,
      }),
    }),
  });
});
