name: Continuous Integration
on: [push]
jobs:
  Continuous-Integration:
    runs-on: ubuntu-latest
    steps:
      - name: Check Out Code
        uses: actions/checkout@v3
      - name: Install Node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
      - name: Install Dependencies
        run: npm clean-install
      - name: Lint Markdown
        run: npm run lint:md
      - name: Lint TypeScript
        run: npm run lint:ts:all
      - name: Type Check Constraint-Engine
        run: cd packages/constraint-engine && npx tsc
      - name: Test Rat
        run: npm run test:framework --workspace rat-test
      - name: Test Mouse
        run: npm run test:framework --workspace mouse-test
      - name: Lint Constraints
        run: npm run lint:constraints

